### ISSUE TITLE
problem with run example/netgear_6220_mips32el_linux.py

### ISSUE THREAD

**Issue by qq963258qq** [qilingframework/qiling#776]
***Describe the bug**
I run example/netgear_6220_mips32el_linux.py, and the it crash "qiling.exception.QlErrorExecutionStop: Dynamic library .init() failed!"

**Sample Code**
As same as example/netgear_6220_mips32el_linux.py
And I change 'multithread=False' to 'multithread=True'

**Screenshots**
![image](https://user-images.githubusercontent.com/73210662/115561777-7a209480-a2e8-11eb-922a-69eecbb3432d.png)

**Comment by wtdcode** [comment]
Seems to be introduced in #772

**Comment by qq963258qq** [comment]
I have updated the version to the lastest dev, but it still have the same problem.

**Comment by xwings** [comment]
try dev ?

**Comment by wtdcode** [comment]
Solved in 6a30e9e4c1eebe4d3338fab47af875ea7d0f6bcb

**Comment by qq963258qq** [comment]
I have tried the latest dev version qiling again, but it still have the same problem...
![image](https://user-images.githubusercontent.com/73210662/116338312-1e856800-a80e-11eb-9b56-7d7f8e890158.png)

**Comment by wtdcode** [comment]
> I have tried the latest dev version qiling again, but it still have the same problem...
> ![image](https://user-images.githubusercontent.com/73210662/116338312-1e856800-a80e-11eb-9b56-7d7f8e890158.png)

Where do you get the rootfs?

**Comment by qq963258qq** [comment]
> > I have tried the latest dev version qiling again, but it still have the same problem...
> > ![image](https://user-images.githubusercontent.com/73210662/116338312-1e856800-a80e-11eb-9b56-7d7f8e890158.png)
> 
> Where do you get the rootfs?

https://www.downloads.netgear.com/files/GDC/R6220/R6220-V1.1.0.106_1.0.1.zip

**Comment by qq963258qq** [comment]
I have already solved the "qiling.exception.QlErrorExecutionStop: Dynamic library .init() failed!" problem.
I modified my script as below:
before
```
my_netgear(["./rootfs/netgear_r6220/bin/mini_httpd",  "-d", "/www", "-r", "NETGEAR R6220", "-c", "**.cgi", "-t", "300"], "./rootfs/netgear_r6220")
```
after
```
my_netgear(["rootfs/netgear_r6220/bin/mini_httpd",  "-d", "/www", "-r", "NETGEAR R6220", "-c", "**.cgi", "-t", "300"], "rootfs/netgear_r6220")
```

but it still have another problem...
![image](https://user-images.githubusercontent.com/73210662/117648169-7930a380-b1c0-11eb-9134-9efb2308ab72.png)


BTW...
I use qltool to emulate the binary, and it seems to work (the port 8080 is open).
the command is: `qltool run -f rootfs/netgear_r6220/bin/mini_httpd --rootfs rootfs/netgear_r6220/ -m `


please help me solve the problem, thanks!

**Comment by xwings** [comment]
If qltools works, there is no reason your script is not working. Check the profile and reassign a correct one ?

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
